# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
	# Hopping
	{ on = "i", run = "arrow prev", desc = "Previous file" },
	{ on = "k", run = "arrow next", desc = "Next file" },

	# Navigation
	{ on = "j", run = "leave", desc = "Back to the parent directory" },
	{ on = "l", run = "enter", desc = "Enter the child directory" },

	{ on = "<Left>",  run = "leave", desc = "Back to the parent directory" },
	{ on = "<Right>", run = "enter", desc = "Enter the child directory" },

	{ on = "J", run = "back",    desc = "Back to previous directory" },
	{ on = "L", run = "forward", desc = "Forward to next directory" },

	# Seeking
	{ on = "I", run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = "K", run = "seek 5",  desc = "Seek down 5 units in the preview" },
]
